### ISSUE TITLE
Classification for detecting atypical behaviour in ASD

### ISSUE THREAD

**Issue by filosi** [webvalley2015/PhysioWat#16]

**Comment by dingvale** [comment]
Input: features extracted from wearable sensor data, first by emulating stereotypies characteristic of ASD, then (possibly field data, but not counting on it). 
Output: quantification & classification of the movements and matching to possible characteristics. Nicola brought up the point that it can be hard to tell whether or not a motion is a stereotypy, or actually a typical method to reduce stress/anxiety.

**Comment by dingvale** [comment]
Notes from research on decision tree:
Need to find factors from data to use as decision-making nodes in tree, i.e. not just mean & variance, but perhaps some way to quantify "frequency" of movement. If speed is an issue, we need to find a way to balance number of decision nodes and classification accuracy, which can be achieved through testing.

**Comment by dingvale** [comment]
Notes from Elina:
Sliding window signals for activity recognition: features- mean acceleration, signal energy, signal frequency-domain entropy, signal correlation
