### ISSUE TITLE
mean and variance npy files for ASD data

### ISSUE THREAD

**Issue by dingvale** [webvalley2015/PhysioWat#33]
data_mean.npy and data_var.npy files for both claire_ASD.txt and claire_control.txt uploaded under Classification folder in GitHub. I talked to Riccardo this morning - he is working on this and will commit to GitHub today.

**Comment by Manciukic** [comment]
Committed on github in PhysioWat/preproc/scripts/processing_scripts/output folder. I removed norm as you asked me.
I've also sent you the files by mail
