### ISSUE TITLE
another name for the project? or keep PhysioWat?

### ISSUE THREAD

**Issue by Annalisa97** [webvalley2015/PhysioWat#37]

**Comment by AntoninaChepa** [comment]
keep PhysioWAT

**Comment by cgoecknerwald** [comment]
what about PhysioWatt, we can kind of keep the same name, but the watt is the unit of power

**Comment by Annalisa97** [comment]
Physio Wearable Activities Trackers Technology

**Comment by Annalisa97** [comment]
Physio Wearable Analitics Techs
